### ISSUE TITLE
Design Docs

### ISSUE THREAD

**Issue by ronilbhatia** [LamVu1/Sribbble-Clone-App#1]
# Wiki Page Home

- [ ] Is the first page you see upon entering the wiki
- [ ] Contains a welcome message
- [ ] Contains a link/placeholder for a link to the live page
- [ ] All links in the right sidebar should contain each wiki page and link to the correct page
- [ ] Correctly formatted
    - [ ] each wiki page is listed in bullet points
    - [ ] all links route the correct page

## Comments

---

# MVP List

- [ ] Should have 7 MVPs.
    - [ ] 3 of those are User Auth, Heroku, and Production README.
    - [ ] The other 4 are from the [MVP List](https://github.com/appacademy/curriculum/blob/master/full-stack-project/proposal/mvp-list.md) or they have clarified them with you
- [ ] Contains a description sentence of the app
- [ ] Includes two to three detailed bullets on functionality and presentation of feature
- [ ] At least one CRUD feature, which states what CRUD operations are planned (creation, reading, updating, deletion)
- [ ] Estimates how long it will take the code each MVP
- [ ] Correctly formatted
    - [ ] MVPs are listed in an ordered list
    - [ ] Each MVP is broken down into bullet points

## Comments
* Looks good overall! I don't think the job stuff should be an MVP - it's a cool feature of their site but I would focus more on the posts and their associated components like comments, likes and tags. Jobs seems like a completely separate undertaking, and would be made better as a late bonus feature. I would make comments your 4th MVP instead, since you already have incorporated it into your design docs.

---

# Database Schema

- [ ] Contains correct datatypes
- [ ] Contains appropriate constraints/details
    - [ ] primary key
    - [ ] not null
    - [ ] unique
    - [ ] indexed
    - [ ] foreign key
- [ ] Contains bullet points after the table that state which foreign keys will reference to which table, or references to the associations which will be made
  - [ ] foreign key and table name are lowercased, snake_cased and `back_ticked`
- [ ] Correctly formatted
    - [ ] schema is written in a table format
    - [ ] the table's name are lowercased, snake_cased and `back_ticked`
    - [ ] the table header column names are bolded
    - [ ] columns names are lowercased and snaked_cased and `back_ticked`

## Comments
* For your `followers` table, I think that `author_id` doesn't really make sense as one of the column names, since follows don't really involve any form of authorship. I would instead make the columns `user_id` and `follower_id` where `user_id` is the person _being followed_ and `follower_id` is the one following the other user.
* Remove `unique: true` for `comments` table on `[:post_id, :user_id]` - but you can keep the index.
---

# Sample State

- [ ] State shape is flat!
- [ ] State's keys are camelCased
- [ ] All keys within the values in the state are accessible in the schema
- [ ] Correctly formatted
    - [ ] Sample state is rendered with triple backticks, and the language ` ```javascript...``` `). This will display the state as a code block instead of a giant line of text 
    - [ ] Top level slices
        - [ ] `entities`
        - [ ] `session`
        - [ ] `errors` (here or in `ui`)
        - [ ] `ui` (if needed)
    - [ ] Should NOT have nested slices, aka  `comments` inside of `posts`
      + Some info from other tables is ok, for instance:
        + the author username and imageurl for a post. basically any info that the user can't change
        + like count and a boolean on whether the user likes the post instead of a likes slice

## Comments
* Great job on the sample state - very thorough! To get the proper formatting, wrap the entire object in triple backticks (```). In the opening triple backtick throw `js` at the end and it will format it as javascript!

---

# Backend Routes

- [ ] Contains the following sections: HTML, API Endpoints(Backend)
- [ ] Each route has a description
- [ ] API Endpoint routes contains wildcard variables written in `snake_case`
- [ ] Routes does not contain [superfluous routes](https://github.com/appacademy/curriculum/blob/master/rails/readings/routing-part-ii.md)
- [ ] Have API routes that will allow the front end to get all info it needs and does not have unneeded routes:
    + probably doesn't need a `GET likes` api endpoint because that info comes through the post show

## Comments
* Your routes for creating, editing, and deleting a comment do not need to be nested beneath a post. When you create a post, you can send the associated `post_id` up with the rest of the post data in the request. For editing and deleting, since the comment already exists we only need its `id` in order to update/delete the post so including the `post_id` is unnecessary.
* You probably don't need your `GET` routes for `saves` and `follows` - I get what you are trying to do with them, but most likely when you fetch a user, you will also fetch their followers as well as their saved posts. It doesn't hurt to have these routes in there, but I just don't think you'll end up using them.
* I'm confused by the `GET /api/users` route - not sure what you mean by returns the user information of displayed posts. This would make sense as a route with which you could search users so I'm good with that part. Do you also need something like a `GET /api/users/:id` route to fetch info for a specific user?
* Do you need a dedicated route for searching for posts? Maybe something like `/api/posts/search` - alternatively you can use your `/api/posts` route but right now it sounds like that's just returning every post? 
---

# Frontend Routes

- [ ] Frontend routes contains wildcard variables written in `camelCase`
- [ ] Correctly formatted
    - [ ] Routes are displayed with `inline coding text` (backticks)

## Comments
* Good job on the frontend routes! The only thing I think is missing is a `/search` or some other front end route that would display search results (essentially your `PostIndex` again as the component).

**Comment by LamVu1** [comment]
Completed the project proposal documents including:
-  Backend Routes
-  Frontend Routes
-  MVP List
-  Sample State
-  Schema
